### ISSUE TITLE
What values to use for differential marker expression

### ISSUE THREAD

**Issue by singlecellfan** [ChristofSeiler/CytoGLMM#1]
Hi,

thanks a lot for the nice package. I wanted to give it a try and was a bit unsure what type of values to use. In the tutorial and the paper you mention that batch correction should be applied and an inverse hyperbolic sine transformation be performed.
So does that mean you take the values after batch correction (e.g. by Cytonorm) and transform them?

Or should this type of transformation be directly performed on the raw values or on the logicle transformed data?

Thank you very much in advance!

**Comment by ChristofSeiler** [comment]
Hi,

Yes, we take the values after batch correction and transformation. As you stated, a popular transformation for mass cytometry is `asinh(x/5)`. That's what we used in the tutorial at the end of section 2.

I hope this help!
